Checkin the first photon fast simulation module based on GAN
LArSoft/larsimdnn pull request #1
Opened 2021-01-28 21:06 UTC by Healthborn

Checkin include:
- change the name of the directory to avoid conflict;
- the CMakeLists.txt
- the code for the module
- the code for the tool

2021-02-01 20:33 UTC, lgarren commented
@Healthborn @knoepfel  I'm taking a first look at this.  
First, my apologies, but please remove find_ups_product( eigen ) from the top level CMakeLists.txt file.  The ups eigen package is not used by larsimdnn.   Second, please update the larsim version to v09_08_00 in ups/product_deps.  Third, extensions matter.  If a file is meant to be included in a library, it needs the .cxx extension.  The .cc extension is used only for plugins.

2021-02-01 20:37 UTC, lgarren requested changes

2021-02-01 20:37 UTC, lgarren commented on larsimdnn/PhotonSimulation/CMakeLists.txt
> +                       ROOT::GenVector
Please remove the SERVICE_LIBRARIES block.  There are no plugins in this directory.

2021-02-01 20:37 UTC, lgarren commented on larsimdnn/PhotonSimulation/CMakeLists.txt
> +                        ROOT::Gpad
Please remove the MODULE_LIBRARIES block.  There are no plugins in this directory.

2021-02-01 20:39 UTC, lgarren commented on larsimdnn/PhotonSimulation/CMakeLists.txt
> +                        ROOT::Gpad
Oh, crud.  Sorry.  There is a module.

2021-02-01 20:54 UTC, lgarren commented
@Healthborn @knoepfel 
After local modifications, I have a successful build which creates the following libraries.   I'm attaching a patch file.  The patch does not include renaming TFLoader.cc to TFLoader.cxx.  Kyle will be reviewing the code.
liblarsimdnn_PhotonSimulation_PDFastSimGAN_module.so
liblarsimdnn_PhotonSimulation_TFLoaderTools.so
liblarsimdnn_PhotonSimulation_TFLoaderTools_TFLoaderGAN_tool.so

Have to rename the file to attach.
[larsimdnn.patch.log](https://github.com/LArSoft/larsimdnn/files/5906714/larsimdnn.patch.log)

2021-02-01 21:07 UTC, Healthborn commented
thanks a lot @lgarren, a bit busy this week. I will also exam the code.

2021-03-15 15:51 UTC, lgarren commented
@Healthborn any progress?

2021-03-15 18:54 UTC, closed without merging